version: "3"
services:
  web:
    image: nginx
    container_name: web_page
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "4201:80"
    environment:
      - NGINX_HOST=example.com
      - NGINX_port=80
    links:
      - database:db

  database:
    image: postgres
    container_name: postgres_db
    volumes:
      - ./dumps:/tmp/
    ports:
      - "4300:5432"
